# Generated by Django 5.2 on 2025-04-10 18:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(max_length=15)),
                ('initial_capital', models.FloatField()),
                ('mode', models.CharField(choices=[('testing', 'Testing'), ('intraday', 'Intraday'), ('daily', 'Daily')], max_length=10)),
                ('num_days', models.IntegerField()),
                ('news_query', models.CharField(blank=True, max_length=255, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('intraday', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('price', models.FloatField()),
                ('action', models.CharField(max_length=10)),
                ('portfolio_value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='trading.tradingsession')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_history', to='trading.tradingsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
